name: Automatically crawl CVEs 
on: push


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Crawl CVEs
      run: |-
        python main.py -mg

    # 若该时间段没有 CVE， 则 file://cache/mail.dat 文件不会生成，从而不发送邮件
    - name: Send mail
      uses: lyy289065406/action-send-mail@v2
      with:
        server_address: ${{ secrets.MAIL_SMTP }}
        server_port: 465
        username: ${{ secrets.MAIL_USER }}
        password: ${{ secrets.MAIL_PASS }}
        from: ${{ secrets.MAIL_USER }}
        to: ${{ secrets.MAIL_RECV }}
        subject: 威胁情报播报
        body: file://cache/mail.dat
        content_type: text/html

    # readme-bot 是 Github runner 的固定账号，不用改
    - name: Commit and push Github page (if changed)
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "Updated by Github Robot" || exit 0
        git push
